Controllers/Tablica_ogloszenController.cs
using SerwisSamochodowy.Baza_danych;
using SerwisSamochodowy.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SerwisSamochodowy.Controllers
{
    public class Tablica_ogloszenController : Controller
    {

        private Baza_samochodowEntities _samochody_baza;
        public Tablica_ogloszenController()
        {
            _samochody_baza = new Baza_samochodowEntities();
        }

        public ActionResult Tablica()
        {
            IEnumerable<Tablica_ogloszen> Tablica_ogloszen_lista = (from _lista_samochody in _samochody_baza.Samochodies
                        join       
                        _lista_kategorie in _samochody_baza.Kategories
                        on _lista_samochody.Kategoria_ID equals _lista_kategorie.Kategoria_ID
                        select new Tablica_ogloszen()
                        {
                            Zdjecie = _lista_samochody.Zdjecie,
                            Kategoria_samochodu = _lista_kategorie.Kategoria_nazwa,
                            Marka = _lista_samochody.Marka,
                            Model = _lista_samochody.Model,
                            Kolor = _lista_samochody.Kolor,
                            Rok_produkcji = _lista_samochody.Rok_produkcji,
                            Przebieg = _lista_samochody.Przebieg,
                            Rodzaj_paliwa = _lista_samochody.Rodzaj_paliwa,
                            Nr_vin = _lista_samochody.Nr_vin,
                            Nr_kontaktowy = _lista_samochody.Nr_kontaktowy,
                            Opis = _lista_samochody.Opis,
                            Cena = _lista_samochody.Cena                        
                        }
                        ).ToList();
            return View(Tablica_ogloszen_lista);
        }
     
    }
}

Controllers/UzytkownikController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SerwisSamochodowy.Controllers
{
    public class UzytkownikController : Controller
    {


        public ActionResult Profil()
        {
            if (Session["Login"] != null)
            {
                ViewBag.Login = Session["Login"];
                return View();
            }
            else
            {
                return RedirectToAction("Logowanie", "Konto");
            }
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ogłoszenia samochodowe</title>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MyCar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Ogłoszenia", "Tablica", "Tablica_ogloszen")</li>
                </ul>
                @Html.Partial("_Logowanie")
            </div>      
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MyCar</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Logowanie.cshtml
@if (Session["Login"] == null)
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("Rejestracja", "Rejestracja", "Konto")
        </li>
        <li>
            @Html.ActionLink("Logowanie", "Logowanie", "Konto")
        </li>

    </ul>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("" +Session["Login"], "Profil", "Uzytkownik")
        </li>
        <li>
            @Html.ActionLink("Wyloguj", "Wylogowanie", "Konto")
        </li>

    </ul>
}